/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("xyz.jpenilla.run-paper") version "3.0.2"
    id("com.gradleup.shadow") version "9.2.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.noxcrew.com/public")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.noxcrew.noxesium.paper)
    api(libs.com.konghq.unirest.java)
    api(libs.org.json.json)

    shadow(libs.com.noxcrew.noxesium.paper)
    shadow(libs.com.konghq.unirest.java)
    shadow(libs.org.json.json)

    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.org.projectlombok.lombok)

    annotationProcessor(libs.org.jetbrains.annotations)
    annotationProcessor(libs.org.projectlombok.lombok)
}

group = "me.superneon4ik"
version = "3.1.0-dev"
description = "NoxesiumUtils"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.processResources {
    val props = mapOf("version" to version)
    inputs.properties(props)
    filteringCharset = "UTF-8"
    filesMatching(listOf("paper-plugin.yml", "plugin.yml")) {
        expand(props)
    }
}

tasks {
    runServer {
        minecraftVersion("1.21.8")
    }
}