name: NoxesiumUtils
author: SuperNeon4ik
description: Communicate with Noxesium with ease.
version: '${project.version}'
main: me.superneon4ik.noxesiumutils.NoxesiumUtilsPlugin
api-version: 1.21
website: https://github.com/SuperNeon4ik/NoxesiumUtils

depend: [ CommandAPI ]

permissions:
  noxesiumutils.about:
    description: Run /noxesiumutils.
  noxesiumutils.check:
    description: Run /noxesiumutils check & clientSettings.
  noxesiumutils.reload:
    description: Run the reload config command
  noxesiumutils.serverrules:
    description: Access ServerRule commands in /noxesiumutils.
  noxesiumutils.entityrules:
    description: Access EntityRule commands in /noxesiumutils.